- includes/delete_method.hpp
- sources/CMakeLists.txt
- sources/delete_method.cpp
- test/CMakeLists.txt
- test/delete_method_test.cpp
- 파일 삭제 기능 구현
- 테스트 코드 추가
resolved: https://github.com/keonwoo98/webserv/issues/7
> DELETE 메서드 구현

- sources/CMakeLists.txt
- sources/date.cpp
- IMF-fixdate 형식의 date 생성 기능
resolved https://github.com/keonwoo98/webserv/issues/19
> date 기능 구현

- includes/location.hpp
- includes/server.hpp
- sources/config_parser.cpp
- sources/location.cpp
- sources/server.cpp
> Location ,Server add  getter, setter  

- app/CMakeLists.txt
- includes/post_method.hpp
- sources/CMakeLists.txt
- sources/post_method.cpp
- test/CMakeLists.txt
- test/get_method_test.cpp
- test/post_method_test.cpp
- post 같은경우에는 존재 하는 파일에 요청이 들어왔을때 get과 같은 response를 보내줘서, 그냥 get이랑 같게 해줬습니다.
- 그리고 cgi 인 경우에는 따로 처리하진 않았는데,  https://github.com/keonwoo98/webserv/issues/32 할 예정입니다.
> POST 메서드 구현

- includes/uri.hpp
- sources/uri.cpp
> feat: uri 출력 연산자 오버로딩 추가

- includes/character_const/character_color.hpp
- includes/character_const/character_const.hpp
character_const.hpp, character_color.hpp 추가
> feat: 문자 관련 상수 및 출력 문자 색 및 형태 관련 상수 추가

- app/main.cpp
- conf/default.conf
- conf/example.conf
- includes/config/config_parser.hpp
- includes/config/location.hpp
- includes/config/server.hpp
- sources/config/config_parser.cpp
- sources/config/server.cpp
https://github.com/keonwoo98/webserv/issues/29
> Config Parsing 구조 변경 및 Refactoring

- .gitignore
- app/main.cpp
- conf/default.conf
- conf/example.conf
- includes/character_const/character_color.hpp
- includes/config/config_parser.hpp
- includes/config/location.hpp
- includes/config/server.hpp
- sources/config/config_parser.cpp
- sources/config/server.cpp
- sources/core/client_socket.cpp
- sources/core/webserv.cpp
- sources/request/request_parser.cpp
- 문자 속성 (이스케이프 시퀀스 추가 및 수정)
- conf파일 결과 및 request 결과 출력 수정
> 디버깅용 출력 변경

- includes/response/date.h
- includes/response/header.h
- includes/response/http_version.h
- includes/response/response_message.hpp
- includes/response/status_code.hpp
- includes/response/status_line.h
- sources/CMakeLists.txt
- sources/response/date.cpp
- sources/response/header.cpp
- sources/response/http_version.cpp
- sources/response/response_message.cpp
- sources/response/status_line.cpp
- test/CMakeLists.txt
- test/header_test.cpp
- test/response_message_test.cpp
- test/status_line_test.cpp
> response message 리팩토링 & 기능 추가

- sources/core/webserv.cpp
> fix: ListenSocket 삭제

- app/main.cpp
- includes/core/client_socket.hpp
- includes/core/server_socket.hpp
- includes/core/socket.hpp
- includes/core/webserv.hpp
- sources/core/client_socket.cpp
- sources/core/server_socket.cpp
- sources/core/socket.cpp
- sources/core/webserv.cpp
- Config 변경에 의한 use_type을 사용할 수 있도록 리팩토링
> refactor: use_type을 사용하도록 변경

- includes/config/config_parser.hpp
- includes/config/config_utils.hpp
- includes/config/error_pages.hpp
- includes/config/index.hpp
- includes/config/location_info.hpp
- includes/config/server_info.hpp
- sources/config/config_parser.cpp
- sources/config/config_utils.cpp
- sources/config/error_pages.cpp
- sources/config/index.cpp
- sources/config/location_info.cpp
- sources/config/server_info.cpp
https://github.com/keonwoo98/webserv/issues/82
> Config : Server, Location 블록의 Index, ErrorPages 클래스화

- includes/config/server_info.hpp
- sources/config/config_parser.cpp
- sources/config/server_info.cpp
Error Log는 logs/error.log에 쌓인다.
error.log의 경로는 ServerInfo 클래스 안에 static 변수로 선언되어 있다.
> Default Error log 경로 설정

- includes/config/server_info.hpp
- sources/config/server_info.cpp
config 파일의 port 번호가 0 ~ 65535의 범위 밖에 있으면 throw exception
> Config : port 범위(0 ~ 65535) 검사

- includes/config/location_info.hpp
- includes/config/server_info.hpp
- sources/config/location_info.cpp
- sources/config/server_info.cpp
정수를 참조하는 부분 그냥 값으로 전달, 반환하도록 수정했습니다.
(branch 삭제 X)
> refactor: const int &를  int로 수정

- includes/core/event_executor.hpp
- sources/core/event_executor.cpp
- sources/core/kqueue_handler.cpp
- sources/core/socket.cpp
- sources/core/webserv.cpp
- 각 함수 내에서 kqueue handler를 사용하도록 구조 변경
> refactor: kqueue handler 사용하도록 변경

- .gitignore
- includes/core/client_socket.hpp
- includes/core/server_socket.hpp
- includes/core/socket.hpp
- includes/core/webserv.hpp
- sources/core/client_socket.cpp
- sources/core/event_executor.cpp
- sources/core/server_socket.cpp
- sources/core/socket.cpp
ServerSocket은 bind시 address 정보를 저장.
ClientSocket은 accept시 accept요청을 한 클라이언트의 address 정보를 저장.
> ServerSocket, ClientSocket에서 address 가지고 있도록 수정

- includes/response/response_message.hpp
- sources/response/response_message.cpp
> feat: Response Message Add Location 기능 추가

- includes/request/request_message.hpp
- sources/request/request_message.cpp
- sources/request/request_message_getter_setter.cpp
> request_message 메서드 이름 변경

- includes/core/socket.hpp
- sources/core/server_socket.cpp
- sources/core/socket.cpp
- test/CMakeLists.txt
- test/core/socket_addr.cpp
> feat: host 값을 ip 문자열로 바꿔주는 기능

- sources/core/event_executor.cpp
> fix: access log 버그 수정

- includes/config/error_pages.hpp
- includes/config/index.hpp
- includes/config/location_info.hpp
- includes/config/server_info.hpp
- sources/config/error_pages.cpp
- sources/config/index.cpp
- sources/config/location_info.cpp
- sources/config/server_info.cpp
- Location에서 Error page path 바로 반환 (민준 요구사항)
- error_page, index 출력 연산자 오버로딩
> Refactor / Config

- includes/response/response_message.hpp
- sources/core/event_executor.cpp
- sources/core/webserv.cpp
- sources/response/response_message.cpp
- Response::AddConncetion추가
- Request Done일 때 혹은 HttpException일 때 AddConnection 호출
> Response메시지에 Connection 헤더 추가

- sources/core/event_executor.cpp
close시 client_socket을 제대로 해제하지 않아 seg fault가 났던 문제 수정
> fix: segfault 수정

- includes/core/event_executor.hpp
- sources/core/event_executor.cpp
- sources/core/webserv.cpp
SendResponse에서 포인터를 값으로 전달함에 따른 오류 #162 수정
> Fix: SendResponse()가 Udata의 포인터를 값으로 호출하는 문제

- includes/response/cgi_handler.hpp
- sources/core/event_executor.cpp
- sources/response/cgi_handler.cpp
GET method일 때 php-cgi 결과를 그대로 전달
결과에 대한 파싱은 아직 처리되지 않았음
``/cgi-bin/get_result.php?id=blahblah&age=blahblah`` 로 접속하여 테스트 가능
> cgi GET method 구현

- includes/core/resolve_uri.hpp
- sources/core/resolve_uri.cpp
> feat: URI decoding

- conf/test1.conf
- erase_all_logs.sh
- includes/request/request_message.hpp
- includes/request/request_parser.hpp
- sources/core/event_executor.cpp
- sources/core/webserv.cpp
- sources/request/request_chunked_parser.cpp
- sources/request/request_message.cpp
- sources/request/request_parser.cpp
- sources/request/request_validation.cpp
Tester 실행에 필요한 파일 및 디렉토리 생성
1. 필요 시 conf file 수정 및 생성
2. 터미널 두 개 실행
3. 터미널 1에서 ./tester localhost:8181 로 테스터 실행
4. 터미널 2에서 ./webserv conf/test1.conf 로 웹서브 실행
5. 테스터에서 enter 입력 하면서 확인
순서로 테스트 하면 됨.
> Tester 실행에 필요한 파일 및 디렉토리 생성

- includes/response/cgi_handler.hpp
- sources/core/kqueue_handler.cpp
- sources/response/cgi_handler.cpp
- env_list delete
- Logger event
> fix: 메모리 누수

- includes/core/kqueue_handler.hpp
- sources/core/event_executor.cpp
- sources/core/kqueue_handler.cpp
- sources/core/webserv.cpp
- kevent에서 트리거된 이벤트를 받는 사이즈를 늘림
> fix: kevent error 수정.

- sources/core/logger.cpp
> fix: write 예외처리
